// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjihgfzjgfejokgumppz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqaWhnZnpqZ2Zlam9rZ3VtcHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NjE5MDUsImV4cCI6MjA3ODIzNzkwNX0.uUBxVXbhrFQu0sRQDsM9wSUtqeQZMoElPhXZJBI0RIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});